### PR TITLE
Updated bdk-ffi to v0.10.0 (bdk 0.23)

### PR DESCRIPTION
**Pull request by notmandatory**
I also updated the README example to match current bdk-ffi API.

### CODE REVIEW

**Comment by notmandatory** [comment]
@thunderbiscuit I know this isn't your specialty but I need an approval to merge this PR and then I'll make the next `bdk-swift` release. I don't want to get another YOLO badge. 🙄

**Comment by thunderbiscuit** [comment]
No problem! I don't mind helping out on bdk-swift at all. 

Where is the version number bump happening? I can't find a file with a version number 😆.

ACK [7ba5f37](https://github.com/bitcoindevkit/bdk-swift/pull/32/commits/7ba5f3757db60de3db531f3dc1c77c9cee07a1d3).

**Comment by notmandatory** [comment]
Swift packaging doesn't actually put the version anywhere, it only uses the git tag version when adding a dependency. But for this PR I'm only updating the bdk-ffi and the related README fixes.

**Review by thunderbiscuit — APPROVED** [review]
Looks good!

**Pull request merged**
